# Homework 1: Python Exercises

## Dictionary

#### Print the value of age of each key in the following nested dictionary

In [9]:
people = {'person1': {'DOB': 'June', 'age': '25', 'sex': 'M'},
          2: {'DOB': 'May', 'age': '21', 'sex': 'F'}}

# print age of each key
for key in people.keys():
    print(f'The age of {key} is:', people[key]['age'])
    
# or 
for person in people.values():
    print(f'The age of {key} is:', person['age'])

The age of person1 is: 25
The age of 2 is: 21
The age of 2 is: 25
The age of 2 is: 21


#### Add an element.
- Add person 3 using people['person3']={}
- Then set the age of 'person3' to be '29' and print the entire dictionary

In [11]:
people = {'person 1': {'DOB': 'June', 'age': '25', 'sex': 'M'},
          'person 2': {'DOB': 'May', 'age': '21', 'sex': 'F'}, 'person 3': {'DOB': 'July', 'age': '29','sex': 'F'}}

# print age of each key
for key in people.keys():
    print(f'The age of {key} is:', people[key]['age'])
    
# or 
for person in people.values():
    print(f'The age of {key} is:', person['age'])

The age of person 1 is: 25
The age of person 2 is: 21
The age of person 3 is: 29
The age of person 3 is: 25
The age of person 3 is: 21
The age of person 3 is: 29


## Arrays

#### Import package for array operations

In [12]:
import numpy as np

#### Enter the following matrices using ```np.array(...)```: 
$$D=\begin{bmatrix} 6 & 1 & 3\\ 3 & 9 & -3\\ 9 & 3 & 4 \end{bmatrix}$$ 

$$E=\begin{bmatrix} 7 & 6\\ 4 & 2 \end{bmatrix}$$ 

$$F=\begin{bmatrix} 3 & 4\\ -9 & -3 \end{bmatrix}$$


In [10]:

D=np.array([[6,1,3],[3,9,-3],[9,3,4]])
E=np.array([[7,6],[4,2]])
F=np.array([[3,4],[-9,-3]])
print("Matrix D:\n", D)
print("Matrix E:\n", E)
print("Matrix F:\n", F)

Matrix D:
 [[ 6  1  3]
 [ 3  9 -3]
 [ 9  3  4]]
Matrix E:
 [[7 6]
 [4 2]]
Matrix F:
 [[ 3  4]
 [-9 -3]]


#### Extract the following 2x2 matrix from $D$ : $\begin{bmatrix} 9 & -3\\ 3 & 4 \end{bmatrix}$ and assign it to $G$. 
Ref.: see the [Numpy documentation](https://docs.scipy.org/doc/numpy/user/quickstart.html).

In [25]:
# hint
# using the colon notation, for example, D[:2, :2], to select desired submatrix
G=D[1:, 1:]
print ("Matrix G:\n", G)

Matrix G:
 [[ 9 -3]
 [ 3  4]]


#### Find the column-wise sum of the elements in Matrix $D$ using [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.mean.html).

In [29]:

sumC1=np.sum(D[:,0])
sumC2=np.sum(D[:,1])
sumC3=np.sum(D[:,2])
print("Sum of each elements in the first column of Matrix D:", sumC1)
print("Sum of each elements in the second column of Matrix D:", sumC2)
print("Sum of each elements in the third column of Matrix D:", sumC3)


Sum of each elements in the first column of Matrix D: 18
Sum of each elements in the second column of Matrix D: 13
Sum of each elements in the third column of Matrix D: 4


#### Find the row-wise mean of the elements in Matrix $D$ using [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.sum.html).

In [30]:

meanR1=np.mean(D[0,:])
meanR2=np.mean(D[1,:])
meanR3=np.mean(D[2,:])
print("Mean of each elements in the first row of Matrix D:", meanR1)
print("Mean of each elements in the second row of Matrix D:", meanR2)
print("Mean of each elements in the third row of Matrix D:", meanR3)

Mean of each elements in the first row of Matrix D: 3.3333333333333335
Mean of each elements in the second row of Matrix D: 3.0
Mean of each elements in the third row of Matrix D: 5.333333333333333


#### Create a $5 \times 5$ matrix, $J$, which is consisted of standard normal random numbers using [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html).

In [78]:
# hint
# example of generate a $2\times2$ matrix of random numbers from $N(2,3)$.
# np.random.seed(1)    # Please use random see 1 to ensure reproducibility
# np.random.normal(loc=2, scale=3, size=(2,2))
np.random.seed(1)
J=np.random.normal(loc=0, scale=1, size=(5,5))
print("Matrix J:\n", J)


Matrix J:
 [[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
 [-2.3015387   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595]]


#### Compute a new matrix $J$ from $H$, where 1) The negative numbers are replaced by their absolute value, and 2) The positive elements are replaced by 10.
- Use a ```for``` loop to iterate over each (i, j) index pair.
- Use np.where

In [79]:
np.random.seed(1)
J=np.random.normal(loc=0, scale=1, size=(5,5))
H = J.copy()

# 1. Use for loop
len_H = len(H)
for i in range(len_H):
    for j in range(len_H):
        if H[i][j] > 0:
            J[i][j] = 10
        elif H[i][j] < 0 :
            J[i][j] = abs(H[i][j]) 

print('J:\n', J)





J:
 [[10.          0.61175641  0.52817175  1.07296862 10.        ]
 [ 2.3015387  10.          0.7612069  10.          0.24937038]
 [10.          2.06014071  0.3224172   0.38405435 10.        ]
 [ 1.09989127  0.17242821  0.87785842 10.         10.        ]
 [ 1.10061918 10.         10.         10.         10.        ]]


In [76]:
# 2. Use np.where loop
# hint for calculating absolute values using np.abs(): np.abs(-3) = 3
np.random.seed(1)
J=np.random.normal(loc=0, scale=1, size=(5,5))
H = J.copy()
J= np.where(H<=0, np.abs(H), 10)
print('J:\n', J)



J:
 [[10.          0.61175641  0.52817175  1.07296862 10.        ]
 [ 2.3015387  10.          0.7612069  10.          0.24937038]
 [10.          2.06014071  0.3224172   0.38405435 10.        ]
 [ 1.09989127  0.17242821  0.87785842 10.         10.        ]
 [ 1.10061918 10.         10.         10.         10.        ]]


#### Create a result array by adding the following two NumPy arrays. 
#### Then modify the result array by calculating the square root of each element using np.sqrt(). Name the new resultant array 'array3'.

In [86]:
array1 = np.array([[5, 6, 9], [21 ,18, 27]])
array2 = np.array([[15 ,33, 24], [4 ,7, 8]])

# add two arrays array3 = 
sum_array=array1+array2
print("Sum of array1 and array2:\n", sum_array)

# calculate the square root
array3 = np.sqrt(sum_array)
print("The resultant array:\n", array3)

Sum of array1 and array2:
 [[20 39 33]
 [25 25 35]]
The resultant array:
 [[4.47213595 6.244998   5.74456265]
 [5.         5.         5.91607978]]


#### find the index of the largest element in each row of array3 using [numpy.argmax](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html)

In [91]:
array3_maxindex1=np.argmax(array3[0,:])
array3_maxindex2=np.argmax(array3[1,:])
print("The index of the maximum value in the first row of array3:", array3_maxindex1)
print("The index of the maximum value in the second row of array3:", array3_maxindex2)


The index of the maximum value in the first row of array3: 1
The index of the maximum value in the second row of array3: 2


## Comprehension

#### Produce a new list name 'H_list' by flattening $H$ into a 1d array and convert it to a list
Hint: Use [numpy.ndarray.flatten](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) as well as
[numpy.ndarray.tolist](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html).

In [94]:
import numpy as np

# generate H
np.random.seed(1) 
H = np.random.normal(loc=0, scale=1, size=(5,5)) # loc and scale can be ignored if it is standard normal distribution

# flatten and convert
H_list = H.flatten().tolist()


# print
print('H_list:\n', H_list)

H_list:
 [1.6243453636632417, -0.6117564136500754, -0.5281717522634557, -1.0729686221561705, 0.8654076293246785, -2.3015386968802827, 1.74481176421648, -0.7612069008951028, 0.31903909605709857, -0.2493703754774101, 1.462107937044974, -2.060140709497654, -0.3224172040135075, -0.38405435466841564, 1.1337694423354374, -1.0998912673140309, -0.17242820755043575, -0.8778584179213718, 0.04221374671559283, 0.5828152137158222, -1.1006191772129212, 1.1447237098396141, 0.9015907205927955, 0.5024943389018682, 0.9008559492644118]


#### Use list comprehension to modify 'H_list' as follows: 1) replace negative number by their absolute value, and 2) replace positive numbers by 10. Return 'H_list_new' after all operations.
Hint: use 'if else' within list comprehension. Check out this [reference](https://stackoverflow.com/questions/4406389/if-else-in-a-list-comprehension).

In [98]:

np.random.seed(1) 
H = np.random.normal(loc=0, scale=1, size=(5,5)) # loc and scale can be ignored if it is standard normal distribution

H_list = H.flatten().tolist()

H_list_new = H_list
for i in range(len(H_list)):
    if H_list[i] > 0:
        H_list_new[i] = 10
    elif H_list[i] < 0:
        H_list_new[i] = abs(H_list[i])
print('H_list_new:\n', H_list_new)


H_list_new:
 [10, 0.6117564136500754, 0.5281717522634557, 1.0729686221561705, 10, 2.3015386968802827, 10, 0.7612069008951028, 10, 0.2493703754774101, 10, 2.060140709497654, 0.3224172040135075, 0.38405435466841564, 10, 1.0998912673140309, 0.17242820755043575, 0.8778584179213718, 10, 10, 1.1006191772129212, 10, 10, 10, 10]


#### Use zip and comprehension to create a dictionary named 'uta_dict' where the keys are list_a and the values are list_b. 

In [100]:
# create lists

list_a = ['Country', 'State', 'School']
list_b = ['USA', 'Texas', 'UTA']

# Create a dictionary using zip and comprehension
uta_dict = {key: value for key, value in zip(list_a, list_b)}

print(uta_dict)



{'Country': 'USA', 'State': 'Texas', 'School': 'UTA'}


#### Keep elements in list_a that has 'S' in it using list comprehension.

In [101]:
# hint: use if condition, if 'S' in , after the for loop in the list comprehension
# Create list_a
list_a = ['Country', 'State', 'School']
filtered_list = [item for item in list_a if 'S' in item]

print(filtered_list)


['State', 'School']


## Functions

#### Write a function ```sum_square(n)``` that takes as input $n$ and returns $y$, where $$y=\left(1+2^{2}+\cdots+n^{2}\right)=\sum_{k=1}^{n}k^{2}$$
- Use for loop
- Use np.sum()

In [102]:
# using a for loop
def sum_square_for(n):
    y = 0
    for i in range(n+1):
        y += i**2
    return y

In [1]:
# using np.sum()

def sum_square_np(n):
    y = np.sum(np.arange(1, n+1) ** 2)
    return y


## Plots

- Plot $sin(x)$ and $sec(x)$ between $-3\pi$ and $3\pi$ on the same graph, using different colors, line styles, and markers for the two curves. 
- Include a legend to distinguish between the two curves. 
- Add $x$ and $y$ labels, and a title to the plot. 
- You will probably need to use the function ```ylim```, which set the range of $y$ values, to enhance the readability of your plot.
- save the plot as a pdf (dpi=250; tight layout) to the a neighboring folder named 'plot_folder'. Relative path should be used. Hint: the path looks something like './plot_folder/{plot_name}.pdf'

For those who are interested, here is an article about [making publication quality plot using Python](https://github.com/jbmouret/matplotlib_for_papers).

In [1]:
# import necessary packages
import numpy as np
import matplotlib.pyplot as plt


In [4]:
# make and format plot
x = np.linspace(-3 * np.pi, 3 * np.pi, 1000)
y_sin = np.sin(x)
y_sec = 1 / np.cos(x)
plt.figure(figsize=(8, 6))
plt.plot(x, y_sin, color='blue', linestyle='-', marker='o', label=r'$\sin(x)$')
plt.plot(x, y_sec, color='black', linestyle='--', marker='s', label=r'$\sec(x)$')
plt.ylim(-10, 10)
plt.xlabel(r'$x$')
plt.ylabel(r'$y$')
plt.title(r'Plot of $\sin(x)$ and $\sec(x)$ between $-3\pi$ and $3\pi$')
plt.legend()
plt.tight_layout()
plt.savefig('./plot_folder/sin_sec_plot.pdf', dpi=250)
plt.show()

NameError: name 'np' is not defined

## Importing Data

#### Load the data from the Excel file ```taxi.csv```. 
CSV is a plain text format in which values are separated by commas.
Then print the top 5 rows and colum names

In [3]:
# import pandas
import pandas as pd

# import the data using relative path/directory
data = pd.read_csv('taxi.csv')

# print top 5 rows

print(data.head())



    medallion  hack_license vendor_id pickup_datetime dropoff_datetime  \
0  2010000001    2010000001       VTS   1/1/2010 0:00    1/1/2010 0:34   
1  2010000002    2010000002       VTS   1/1/2010 0:00    1/1/2010 0:33   
2  2010000003    2010000003       VTS   1/1/2010 0:00    1/1/2010 0:07   
3  2010000004    2010000004       VTS   1/1/2010 0:00    1/1/2010 0:33   
4  2010000005    2010000005       VTS   1/1/2010 0:00    1/1/2010 0:28   

   passenger_count  trip_time_in_secs  trip_distance  
0                1               34.0          14.05  
1                1               33.0           9.65  
2                1                7.0           1.63  
3                1               33.0          26.61  
4                2               28.0           3.15  


In [23]:
# print column names
print(data.columns)


Index(['medallion', 'hack_license', 'vendor_id', 'pickup_datetime',
       'dropoff_datetime', 'passenger_count', 'trip_time_in_secs',
       'trip_distance'],
      dtype='object')


#### Now compute the average passenger count, average trip time in seconds, and the average trip distance. You may change the columns to lists and do the computation or you may explore the [Pandas documentation](http://pandas.pydata.org/pandas-docs/stable/10min.html) for native functionality.

In [1]:
df.columns.tolist()
print(taxi['vendor_id'])
print(list(taxi['vendor_id']))

NameError: name 'df' is not defined

In [2]:
# compute the average values
avg_passenger_count = df["passenger_count"].mean()
avg_trip_time = df["trip_time_in_secs"].mean()
avg_trip_distance = df["trip_distance"].mean()

print(f"Average Passenger Count: {avg_passenger_count}")
print(f"Average Trip Time (secs): {avg_trip_time}")
print(f"Average Trip Distance: {avg_trip_distance}")


NameError: name 'df' is not defined

#### Create two histograms:
- One showing the distributation of trip time in seconds
- The other showing the distribution of trip distance. 

Make sure you label the axes and give the histograms titles. This may also be accomplished using functionality within the Pandas package (examples can be found [here](https://sparkbyexamples.com/pandas/pandas-plot-a-histogram/)), but it can also be done using ```matplotlib.pyplot```, as you have seen before.

## Reading Assignment

#### Read 'Python naming conventions'(https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html) and give a example name of a Python function and a constant.

In [99]:
# a function


# a constant


# a package


#### Describe a [*magic number*](https://goo.gl/nYMuuG) and the benefits of avoiding 'Unnamed numerical constants' in your code.

**Answer here**

#### <font color=red> Check your previous code in this notebook to make sure there is no magic number and the naming follows the convention.</font>

#### If you want to know more about Python coding styles, read ["Code Style" from "A Hitchhiker's Guide to Python"](https://docs.python-guide.org/writing/style/). You don't need to follow every detail on the first pass, but it will serve as a useful reference throughout the semester as your base coding improves.

## Check Your Work
#### <font color=red> Make sure you restart the Python kernel and run all of your cells to ensure that the entire notebook executes through without error. This can be done by clicking 'Kernel' and then 'Restart & Run All'. </font> This is the first step in how your homework will be checked.